services:
  - type: web
    name: moksh-flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn flask2:app
    region: oregon  # or change to your preferred region
    envVars:
      - key: FLASK_ENV
        value: production


