services:
  - type: web
    name: flask-old-version
    runtime: python
    buildCommand: ""
    startCommand: gunicorn flask2:,py
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon

